### ISSUE TITLE
center prop's changes doesn't ‌apply

### ISSUE THREAD

**Issue by shayan1998** [map-ir/mapir-vue#3]
hi
I want to use the library on my vue js app and the map looks great but my problem is that changing "center" prop doesn't change anything and still seeing the default location?!!!

**Comment by mhsattarian** [comment]
`center` prop is used only in initialization state and updates are not effective.
in order to **change map's center**, you can store map instance after load like so:

```js
// template
<mapir :apiKey="apiKey" :center="center" @load="onMapLoad"></mapir>

// script
methods: {
    onMapLoad({ map, component }) {
      this.map = component;
    },
}
```

then use this map object and call `setCenter` to change map's center:

```
this.map.setCenter([51.39541625976562, 35.715298012125295]);
```

**Comment by shayan1998** [comment]
> `center` prop is used only in initialization state and updates are not effective.
> in order to **change map's center**, you can store map instance after load like so:
> 
> ```js
> // template
> <mapir :apiKey="apiKey" :center="center" @load="onMapLoad"></mapir>
> 
> // script
> methods: {
>     onMapLoad({ map, component }) {
>       this.map = component;
>     },
> }
> ```
> 
> then use this map object and call `setCenter` to change map's center:
> 
> ```
> this.map.setCenter([51.39541625976562, 35.715298012125295]);
> ```

thank you. that's work
